### PR TITLE
modernize

### PR DESCRIPTION
**Pull request by wojpawlik**

### CODE REVIEW

**Comment by dsblv** [comment]
Thank you! Good catch on reduceRight!

I'm happy to merge f7990a9 and 9f3e874, not sure about version bump. We're not targeting node exclusively and there are some browsers not supporting object spread. (https://caniuse.com/#search=object%20spread)

Dropping dependency is nice though, I feel like just rewriting that part to explicitly created objects would be a win.

**Comment by wojpawlik** [comment]
How about using `Object.assign` (supported by IE11) and bringing back the `apply`? I can also bring back the old Node to CI if you aren't comfortable dropping it.

**Comment by dsblv** [comment]
I'm curious why you felt like making this contribution? Something you had to deal with while using the module?

In my experience it's generally nice for these utility modules to support as many targets as possible. There aren't much code to maintain so syntax doesn't get you anything. I remember converting this  code to es5 by hand for this reason. Felt like babel but manual 😊

I looked at the code a bit and think that instead of copying whole `match`, I'd rather pick only the fields we need later (https://github.com/dsblv/string-replace-async/blob/2827405bbc80d386e20016dfdc31b6ec0ae5a218/index.js#L23-L26). These objects only used internally so it seems safe to change them.

That way we'll be able to drop `object-assign` and also make intent clearer.

I'm cool with adding modern node versions to ci, but it's important to leave oldest supported version there so we know if we break it. This means `apply` will have to stay too.

**Comment by wojpawlik** [comment]
I don't know why I decided to contribute.
It seems CI doesn't run.

**Comment by dsblv** [comment]
This looks great, thank you! I'll look into ci and merge 😌

**Comment by dsblv** [comment]
> I don't know why I decided to contribute.

The reason why I asked was pure curiosity, sorry if it sounded discouraging. Thanks again for your time, it's very much appreciated!

**Pull request merged**
