### PR TITLE
reset lastIndex in case it was changed before

### LINKED ISSUE #1: set lastIndex to 0 for regex.
Reference https://runkit.com/ritz078/596f69dc46969600123cb8b5

### PR DESCRIPTION
**Pull request by ritz078**
fixes #1

### CODE REVIEW

**Comment by dsblv** [comment]
Great catch! This definitely diverges with `String.prototype.replace` behaviour.

Could you please revert code style tweaks so that actual changes are visible? It'd be awesome if you also added a test case that fails before and passes after your change.

Thanks!

**Comment by ritz078** [comment]
@dsblv done

**Comment by dsblv** [comment]
Cool! `instanceof` check is also on point, I missed it in initial review.

Thank you for your contribution! 🎉

**Comment by ritz078** [comment]
can you please do a new release ?

**Comment by dsblv** [comment]
Releasing as we speak.

**Comment by dsblv** [comment]
It's live!

**Comment by ritz078** [comment]
Thanks.

**Pull request merged**
